// TDD slice: p3-parser-input-bounds
//
// These tests specify the direct parser ceilings that must match the existing
// response-size policy. Boundary bodies are generated by encoded UTF-8 byte
// length, not JavaScript string length. Fetched-path tests mock the repository's
// approved axios seam, so no request leaves the test process.

import { afterEach, describe, expect, test } from "bun:test";
import axios from "axios";
import type {
	CalendarFeedConfig,
	CalendarParseOptions,
} from "../models/calendar.model";
import type { FeedTransformerSourceFormat } from "../models/feed-transformer.model";
import type { SitemapFeedConfig } from "../models/sitemap.model";
import {
	fetchAndBuildCalendarItems,
	parseIcsEvents,
} from "../utilities/calendar-feed.utility";
import {
	parseExistingFeed,
	parseExistingFeedContent,
} from "../utilities/existing-feed-parser.utility";
import { extractJsonLd } from "../utilities/json-ld.utility";
import { analyzeJsonLdDrillChain } from "../utilities/json-ld-drill-chain.utility";
import { extractJsonLdItemsFromHtml } from "../utilities/json-ld-extractor.utility";
import {
	fetchAndBuildSitemapItems,
	parseSitemapXml,
} from "../utilities/sitemap.utility";

const EXISTING_FEED_LIMIT = 4 * 1024 * 1024;
const DOCUMENT_LIMIT = 2 * 1024 * 1024;
const JSON_LD_BLOCK_LIMIT = 500_000;

const EXISTING_FEED_MARKER = "existing-feed-input-limit-secret-7f2e";
const SITEMAP_MARKER = "sitemap-input-limit-secret-8a31";
const CALENDAR_MARKER = "calendar-input-limit-secret-9b42";
const HTML_MARKER = "html-jsonld-input-limit-secret-0c53";
const JSON_LD_OVERSIZE_MARKER = "jsonld-oversize-secret-1d64";

const originalAxiosGet = axios.get;

afterEach(() => {
	axios.get = originalAxiosGet;
});

function encodedBytes(value: string): number {
	return new TextEncoder().encode(value).byteLength;
}

/** Build a body of exactly targetBytes while keeping the fixture readable. */
function bodyOfBytes(
	prefix: string,
	suffix: string,
	targetBytes: number,
	fill = "x",
): string {
	const fixedBytes = encodedBytes(prefix) + encodedBytes(suffix);
	if (fixedBytes > targetBytes) {
		throw new Error(
			`Fixture prefix/suffix exceed target (${fixedBytes} > ${targetBytes})`,
		);
	}

	const remaining = targetBytes - fixedBytes;
	const fillBytes = encodedBytes(fill);
	if (fillBytes === 0) throw new Error("Fixture fill must not be empty");
	const repeated = fill.repeat(Math.floor(remaining / fillBytes));
	const remainder = remaining - encodedBytes(repeated);
	return `${prefix}${repeated}${"a".repeat(remainder)}${suffix}`;
}

function limitBodyError(
	action: () => unknown,
	classPattern: RegExp,
	marker: string,
): Promise<void> {
	return (async () => {
		let thrown: unknown;
		try {
			await action();
		} catch (error) {
			thrown = error;
		}

		expect(thrown, "oversize input must be rejected").toBeDefined();
		const message = thrown instanceof Error ? thrown.message : String(thrown);
		expect(message).toMatch(classPattern);
		expect(message).toMatch(/limit|size|bytes|too large|oversize/i);
		expect(message).not.toContain(marker);
	})().then(() => undefined);
}

function rssBody(targetBytes: number, valid: boolean, fill = "x"): string {
	const prefix = `<?xml version="1.0" encoding="UTF-8"?><rss version="2.0"><channel><title>Boundary RSS</title><link>https://example.com/</link><description>`;
	const suffix = valid
		? `</description><item><guid>rss-boundary-1</guid><title>RSS boundary item</title><link>https://example.com/rss-boundary</link></item></channel></rss>`
		: `<!-- ${EXISTING_FEED_MARKER}`;
	return bodyOfBytes(prefix, suffix, targetBytes, fill);
}

function atomBody(targetBytes: number, valid: boolean, fill = "x"): string {
	const prefix = `<?xml version="1.0" encoding="UTF-8"?><feed xmlns="http://www.w3.org/2005/Atom"><title>Boundary Atom</title><id>https://example.com/atom</id><link href="https://example.com/atom"/><subtitle>`;
	const suffix = valid
		? `</subtitle><entry><id>atom-boundary-1</id><title>Atom boundary item</title><link href="https://example.com/atom-boundary"/><updated>2026-01-01T00:00:00Z</updated></entry></feed>`
		: `<!-- ${EXISTING_FEED_MARKER}`;
	return bodyOfBytes(prefix, suffix, targetBytes, fill);
}

function jsonFeedBody(targetBytes: number, valid: boolean, fill = "x"): string {
	const prefix = `{"version":"https://jsonfeed.org/version/1.1","title":"Boundary JSON Feed","home_page_url":"https://example.com/","items":[{"id":"json-boundary-1","title":"JSON boundary item","url":"https://example.com/json-boundary"}],"padding":"`;
	const suffix = valid ? `"}` : `${EXISTING_FEED_MARKER}`;
	return bodyOfBytes(prefix, suffix, targetBytes, fill);
}

const EXISTING_FEED_CASES: Array<{
	name: string;
	format: FeedTransformerSourceFormat;
	valid: (targetBytes: number) => string;
	oversize: (targetBytes: number) => string;
}> = [
	{
		name: "RSS",
		format: "rss",
		valid: (size) => rssBody(size, true),
		oversize: (size) => rssBody(size, false),
	},
	{
		name: "Atom",
		format: "atom",
		valid: (size) => atomBody(size, true),
		oversize: (size) => atomBody(size, false),
	},
	{
		name: "JSON Feed",
		format: "jsonFeed",
		valid: (size) => jsonFeedBody(size, true),
		oversize: (size) => jsonFeedBody(size, false),
	},
];

describe("p3 parser input bounds — existing feeds", () => {
	for (const fixture of EXISTING_FEED_CASES) {
		test(`${fixture.name} accepts exactly 4 MiB and preserves the ordinary item`, () => {
			const content = fixture.valid(EXISTING_FEED_LIMIT);
			expect(encodedBytes(content)).toBe(EXISTING_FEED_LIMIT);

			const parsed = parseExistingFeedContent({
				url: "https://example.com/existing-feed",
				format: fixture.format,
				content,
			});

			expect(parsed.detectedFormat).toBe(fixture.format);
			expect(parsed.items).toHaveLength(1);
			expect(parsed.items[0]).toMatchObject({
				guid:
					fixture.format === "rss"
						? "rss-boundary-1"
						: fixture.format === "atom"
							? "atom-boundary-1"
							: "json-boundary-1",
			});
		});

		test(`${fixture.name} rejects 4 MiB + 1 before its XML/JSON parser`, async () => {
			const content = fixture.oversize(EXISTING_FEED_LIMIT + 1);
			expect(encodedBytes(content)).toBe(EXISTING_FEED_LIMIT + 1);

			await limitBodyError(
				() =>
					parseExistingFeedContent({
						url: "https://example.com/existing-feed",
						format: fixture.format,
						content,
					}),
				/existing[ -]?feed/i,
				EXISTING_FEED_MARKER,
			);
		});
	}

	test("the fetched existing-feed path applies the same 4 MiB ceiling as direct content", async () => {
		const exact = rssBody(EXISTING_FEED_LIMIT, true);
		const calls: string[] = [];
		axios.get = (async (url: string) => {
			calls.push(url);
			return {
				status: 200,
				headers: { "content-type": "application/rss+xml" },
				data: exact,
			};
		}) as typeof axios.get;

		const parsed = await parseExistingFeed({
			url: "http://example.com/existing.xml",
			format: "rss",
		});
		expect(parsed.items[0]?.guid).toBe("rss-boundary-1");
		expect(calls).toHaveLength(1);

		const oversize = rssBody(EXISTING_FEED_LIMIT + 1, false);
		axios.get = (async (url: string) => {
			calls.push(url);
			return {
				status: 200,
				headers: { "content-type": "application/rss+xml" },
				data: oversize,
			};
		}) as typeof axios.get;

		await limitBodyError(
			() =>
				parseExistingFeed({
					url: "http://example.com/existing.xml",
					format: "rss",
				}),
			/existing[ -]?feed/i,
			EXISTING_FEED_MARKER,
		);
		expect(calls).toHaveLength(2);
	});
});

const SITEMAP_CONFIG: SitemapFeedConfig = {
	inputMode: "exact",
	url: "http://example.com/sitemap.xml",
	mode: "urlList",
	maxItems: 10,
	maxUrlsToScan: 10,
	sortOrder: "sitemapOrder",
	dateStrategy: "bestAvailable",
	titleStrategy: "path",
	descriptionStrategy: "none",
};

function sitemapBody(targetBytes: number, valid: boolean, fill = "x"): string {
	const prefix = `<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"><url><loc>https://example.com/boundary-sitemap</loc></url><note>`;
	const suffix = valid ? `</note></urlset>` : `<!-- ${SITEMAP_MARKER}`;
	return bodyOfBytes(prefix, suffix, targetBytes, fill);
}

describe("p3 parser input bounds — sitemap XML", () => {
	test("accepts exactly 2 MiB and preserves the URL entry", () => {
		const xml = sitemapBody(DOCUMENT_LIMIT, true);
		expect(encodedBytes(xml)).toBe(DOCUMENT_LIMIT);

		const parsed = parseSitemapXml(xml, SITEMAP_CONFIG.url);
		expect(parsed.entries).toHaveLength(1);
		expect(parsed.entries[0]?.loc).toBe("https://example.com/boundary-sitemap");
	});

	test("keeps an empty direct sitemap result empty", () => {
		const parsed = parseSitemapXml("", SITEMAP_CONFIG.url);
		expect(parsed.entries).toEqual([]);
		expect(parsed.childSitemaps).toEqual([]);
		expect(parsed.stats).toMatchObject({
			totalUrls: 0,
			totalChildSitemaps: 0,
		});
	});

	test("rejects 2 MiB + 1 before Cheerio parses the sitemap", async () => {
		const xml = sitemapBody(DOCUMENT_LIMIT + 1, false);
		expect(encodedBytes(xml)).toBe(DOCUMENT_LIMIT + 1);

		await limitBodyError(
			() => parseSitemapXml(xml, SITEMAP_CONFIG.url),
			/sitemap/i,
			SITEMAP_MARKER,
		);
	});

	test("the fetched sitemap path applies the same exact/+1 ceiling", async () => {
		const calls: string[] = [];
		const exact = sitemapBody(DOCUMENT_LIMIT, true);
		axios.get = (async (url: string) => {
			calls.push(url);
			return { status: 200, headers: {}, data: exact };
		}) as typeof axios.get;

		const items = await fetchAndBuildSitemapItems(SITEMAP_CONFIG);
		expect(items).toHaveLength(1);
		expect(items[0]?.link).toBe("https://example.com/boundary-sitemap");

		const oversize = sitemapBody(DOCUMENT_LIMIT + 1, false);
		axios.get = (async (url: string) => {
			calls.push(url);
			return { status: 200, headers: {}, data: oversize };
		}) as typeof axios.get;
		await limitBodyError(
			() => fetchAndBuildSitemapItems(SITEMAP_CONFIG),
			/sitemap/i,
			SITEMAP_MARKER,
		);
		expect(calls).toHaveLength(2);
	});
});

const CALENDAR_CONFIG: CalendarFeedConfig = {
	url: "http://example.com/calendar.ics",
	windowDays: 365_000,
	includePastEvents: true,
	expandRecurringEvents: false,
	maxEvents: 10,
	sortOrder: "startAsc",
	dateStrategy: "start",
	linkStrategy: "eventUrl",
	includeCanceled: false,
};

const CALENDAR_PARSE_OPTIONS: CalendarParseOptions = {
	windowDays: 365_000,
	includePastEvents: true,
	expandRecurringEvents: false,
	maxEvents: 10,
	sortOrder: "startAsc",
	includeCanceled: false,
};

function calendarBody(targetBytes: number, valid: boolean, fill = "x"): string {
	const prefix = `BEGIN:VCALENDAR\r\nVERSION:2.0\r\nBEGIN:VEVENT\r\nUID:calendar-boundary-1\r\nSUMMARY:Calendar boundary item\r\nURL:https://example.com/calendar-boundary\r\nEND:VEVENT\r\nX-PADDING:`;
	const suffix = valid ? `\r\nEND:VCALENDAR\r\n` : `\r\n${CALENDAR_MARKER}`;
	return bodyOfBytes(prefix, suffix, targetBytes, fill);
}

describe("p3 parser input bounds — calendar ICS", () => {
	test("accepts exactly 2 MiB and preserves the ordinary event", () => {
		const ics = calendarBody(DOCUMENT_LIMIT, true);
		expect(encodedBytes(ics)).toBe(DOCUMENT_LIMIT);

		const events = parseIcsEvents(ics, CALENDAR_PARSE_OPTIONS);
		expect(events).toHaveLength(1);
		expect(events[0]).toMatchObject({
			uid: "calendar-boundary-1",
			summary: "Calendar boundary item",
		});
	});

	test("keeps an empty direct calendar result empty", () => {
		expect(parseIcsEvents("", CALENDAR_PARSE_OPTIONS)).toEqual([]);
	});

	test("rejects 2 MiB + 1 before event matching/parsing", async () => {
		const ics = calendarBody(DOCUMENT_LIMIT + 1, false);
		expect(encodedBytes(ics)).toBe(DOCUMENT_LIMIT + 1);

		await limitBodyError(
			() => parseIcsEvents(ics, CALENDAR_PARSE_OPTIONS),
			/calendar/i,
			CALENDAR_MARKER,
		);
	});

	test("the fetched calendar path applies the same exact/+1 ceiling", async () => {
		const calls: string[] = [];
		const exact = calendarBody(DOCUMENT_LIMIT, true);
		axios.get = (async (url: string) => {
			calls.push(url);
			return { status: 200, headers: {}, data: exact };
		}) as typeof axios.get;

		const items = await fetchAndBuildCalendarItems(CALENDAR_CONFIG);
		expect(items).toHaveLength(1);
		expect(items[0]?.title).toBe("Calendar boundary item");

		const oversize = calendarBody(DOCUMENT_LIMIT + 1, false);
		axios.get = (async (url: string) => {
			calls.push(url);
			return { status: 200, headers: {}, data: oversize };
		}) as typeof axios.get;
		await limitBodyError(
			() => fetchAndBuildCalendarItems(CALENDAR_CONFIG),
			/calendar/i,
			CALENDAR_MARKER,
		);
		expect(calls).toHaveLength(2);
	});
});

function jsonLdNode(marker: string): string {
	return JSON.stringify({
		"@type": "NewsArticle",
		headline: marker,
		url: `https://example.com/${marker}`,
	});
}

function jsonLdScript(payload: string): string {
	return `<script type="application/ld+json">${payload}</script>`;
}

function withObservedJsonParse<T>(action: () => T): {
	value: T;
	inputs: string[];
} {
	const originalJsonParse = JSON.parse;
	const inputs: string[] = [];
	JSON.parse = ((text: string, reviver?: Parameters<typeof JSON.parse>[1]) => {
		inputs.push(text);
		return originalJsonParse(text, reviver);
	}) as typeof JSON.parse;
	try {
		return { value: action(), inputs };
	} finally {
		JSON.parse = originalJsonParse;
	}
}

function jsonLdPayloadOfBytes(
	targetBytes: number,
	marker: string,
	fill = "x",
): string {
	const prefix = `{"@type":"Thing","marker":${JSON.stringify(marker)},"padding":"`;
	return bodyOfBytes(prefix, `"}`, targetBytes, fill);
}

function htmlDocumentOfBytes(
	targetBytes: number,
	valid: boolean,
	fill = "x",
): string {
	const payload = jsonLdNode("html-boundary-item");
	const prefix = `<html><head>${jsonLdScript(payload)}</head><body><main><div>`;
	const suffix = valid ? `</div></main></body></html>` : `<!-- ${HTML_MARKER}`;
	return bodyOfBytes(prefix, suffix, targetBytes, fill);
}

describe("p3 parser input bounds — HTML and JSON-LD", () => {
	test("accepts exactly 2 MiB of UTF-8 HTML across extraction and drill-chain entry points", async () => {
		const html = htmlDocumentOfBytes(DOCUMENT_LIMIT, true, "é");
		expect(encodedBytes(html)).toBe(DOCUMENT_LIMIT);
		expect(html.length).toBeLessThan(DOCUMENT_LIMIT);

		expect(extractJsonLd(html)).toEqual([
			expect.objectContaining({ headline: "html-boundary-item" }),
		]);
		const extracted = extractJsonLdItemsFromHtml(
			html,
			"https://example.com/article",
		);
		expect(extracted.items).toHaveLength(1);
		expect(extracted.items[0]).toMatchObject({
			title: "html-boundary-item",
			link: "https://example.com/html-boundary-item",
		});
		expect(
			await analyzeJsonLdDrillChain(html, "https://example.com/article"),
		).toEqual([]);
	});

	test("keeps empty direct HTML/JSON-LD results empty", async () => {
		expect(extractJsonLd("")).toEqual([]);
		expect(
			extractJsonLdItemsFromHtml("", "https://example.com/article"),
		).toEqual({
			items: [],
			warnings: ["No JSON-LD nodes found."],
		});
		expect(
			await analyzeJsonLdDrillChain("", "https://example.com/article"),
		).toEqual([]);
	});

	test("rejects 2 MiB + 1 HTML before Cheerio at every JSON-LD HTML boundary", async () => {
		const html = htmlDocumentOfBytes(DOCUMENT_LIMIT + 1, false, "é");
		expect(encodedBytes(html)).toBe(DOCUMENT_LIMIT + 1);
		expect(html.length).toBeLessThan(DOCUMENT_LIMIT + 1);

		await limitBodyError(
			() => extractJsonLd(html),
			/html|json[ -]?ld/i,
			HTML_MARKER,
		);
		await limitBodyError(
			() => extractJsonLdItemsFromHtml(html, "https://example.com/article"),
			/html|json[ -]?ld/i,
			HTML_MARKER,
		);
		await limitBodyError(
			() => analyzeJsonLdDrillChain(html, "https://example.com/article"),
			/html|json[ -]?ld/i,
			HTML_MARKER,
		);
	});

	test("applies the HTML ceiling to fetched drill-chain detail pages before JSON-LD analysis", async () => {
		const listing = `<article><a href="/detail-a">A</a><a href="/detail-b">B</a></article>`;
		const oversizeDetail = htmlDocumentOfBytes(DOCUMENT_LIMIT + 1, true, "é");
		expect(encodedBytes(oversizeDetail)).toBe(DOCUMENT_LIMIT + 1);
		const calls: string[] = [];
		axios.get = (async (url: string) => {
			calls.push(url);
			return { status: 200, headers: {}, data: oversizeDetail };
		}) as typeof axios.get;

		const analysis = await analyzeJsonLdDrillChain(
			listing,
			"http://example.com/list",
		);
		expect(analysis).toEqual([]);
		expect(JSON.stringify(analysis)).not.toContain(HTML_MARKER);
		expect(calls).toHaveLength(2);
	});

	test("counts only non-empty JSON-LD blocks and stops after the first 20 in document order", () => {
		const emptyBlocks = ["", "   ", "\n\t"].map((payload) =>
			jsonLdScript(payload),
		);
		const ordinaryMarkers = Array.from(
			{ length: 20 },
			(_, index) => `ordinary-jsonld-${index + 1}`,
		);
		const html = [
			"<html><head>",
			...emptyBlocks,
			...ordinaryMarkers.map((marker) => jsonLdScript(jsonLdNode(marker))),
			jsonLdScript(jsonLdNode("jsonld-after-20")),
			"</head><body></body></html>",
		].join("");

		const nodes = extractJsonLd(html);
		expect(nodes).toHaveLength(20);
		expect(
			nodes.map((node) => (node as { headline?: string }).headline),
		).toEqual(ordinaryMarkers);
		expect(
			nodes.some(
				(node) =>
					(node as { headline?: string }).headline === "jsonld-after-20",
			),
		).toBe(false);
	});

	test("counts invalid non-empty candidates toward the 20-block parse-attempt budget", () => {
		const invalidCandidates = Array.from({ length: 19 }, (_, index) =>
			jsonLdScript(`{ invalid-jsonld-candidate-${index + 1}`),
		);
		const html = [
			...invalidCandidates,
			jsonLdScript(jsonLdNode("valid-attempt-20")),
			jsonLdScript(jsonLdNode("valid-after-attempt-20")),
		].join("");

		const observed = withObservedJsonParse(() => extractJsonLd(html));
		const nodes = observed.value;
		expect(nodes).toHaveLength(1);
		expect(nodes[0]).toMatchObject({ headline: "valid-attempt-20" });
		expect(observed.inputs).toHaveLength(20);
		expect(
			observed.inputs.some((input) => input.includes("valid-attempt-20")),
		).toBe(true);
		expect(
			observed.inputs.some((input) => input.includes("valid-after-attempt-20")),
		).toBe(false);
		expect(
			nodes.some(
				(node) =>
					(node as { headline?: string }).headline === "valid-after-attempt-20",
			),
		).toBe(false);
	});

	test("keeps invalid early blocks best-effort and continues to a later valid block", () => {
		const html = [
			jsonLdScript("{ this is not JSON"),
			jsonLdScript(jsonLdNode("valid-after-invalid-jsonld")),
		].join("");

		const nodes = extractJsonLd(html);
		expect(nodes).toHaveLength(1);
		expect(nodes[0]).toMatchObject({ headline: "valid-after-invalid-jsonld" });
	});

	test("returns an exactly 500,000-byte UTF-8 block, skips +1 before JSON.parse, and continues", () => {
		const exactPayload = jsonLdPayloadOfBytes(
			JSON_LD_BLOCK_LIMIT,
			"jsonld-exact-boundary",
			"é",
		);
		expect(encodedBytes(exactPayload)).toBe(JSON_LD_BLOCK_LIMIT);
		expect(exactPayload.length).toBeLessThan(JSON_LD_BLOCK_LIMIT);

		const oversizePayload = jsonLdPayloadOfBytes(
			JSON_LD_BLOCK_LIMIT + 1,
			JSON_LD_OVERSIZE_MARKER,
			"é",
		);
		expect(encodedBytes(oversizePayload)).toBe(JSON_LD_BLOCK_LIMIT + 1);

		const observed = withObservedJsonParse(() => {
			const exactNodes = extractJsonLd(
				jsonLdScript(exactPayload) +
					jsonLdScript(jsonLdNode("valid-after-exact-jsonld")),
			);
			const oversizeNodes = extractJsonLd(
				jsonLdScript(oversizePayload) +
					jsonLdScript(jsonLdNode("valid-after-oversize-jsonld")),
			);
			return { exactNodes, oversizeNodes };
		});
		const { exactNodes, oversizeNodes } = observed.value;

		expect(
			observed.inputs.some((input) => input.includes("jsonld-exact-boundary")),
		).toBe(true);
		expect(
			observed.inputs.some((input) =>
				input.includes("valid-after-exact-jsonld"),
			),
		).toBe(true);
		expect(
			exactNodes.some(
				(node) =>
					(node as { marker?: string }).marker === "jsonld-exact-boundary",
			),
		).toBe(true);
		expect(
			exactNodes.some(
				(node) =>
					(node as { headline?: string }).headline ===
					"valid-after-exact-jsonld",
			),
		).toBe(true);
		expect(
			observed.inputs.some((input) => input.includes(JSON_LD_OVERSIZE_MARKER)),
		).toBe(false);
		expect(
			observed.inputs.some((input) =>
				input.includes("valid-after-oversize-jsonld"),
			),
		).toBe(true);
		expect(
			oversizeNodes.some(
				(node) =>
					(node as { marker?: string }).marker === JSON_LD_OVERSIZE_MARKER,
			),
		).toBe(false);
		expect(
			oversizeNodes.some(
				(node) =>
					(node as { headline?: string }).headline ===
					"valid-after-oversize-jsonld",
			),
		).toBe(true);
	});
});
