// Live preview panel — items list / RSS XML / Atom / JSON Feed tabs.

const MOCK_PREVIEW_ITEMS = [
  {
    title: "City council passes 2027 budget",
    link: "https://example.com/news/2026-05-22-city-council-passes-budget",
    pubDate: "Thu, 22 May 2026 16:14:00 GMT",
    description: "The council approved the 2027 fiscal year budget Thursday with provisions for park renovations and a new community center.",
    author: "Sarah Johnson",
    image: "https://example.com/images/budget.jpg",
  },
  {
    title: "Spring festival announced for June",
    link: "https://example.com/news/2026-05-21-spring-festival",
    pubDate: "Wed, 21 May 2026 11:02:00 GMT",
    description: "The annual spring festival returns next month with live music, local food vendors, and a kids' zone.",
    author: "Mike Reyes",
    image: "https://example.com/images/festival.jpg",
  },
  {
    title: "Park renovation begins on the riverfront",
    link: "https://example.com/news/2026-05-20-park-renovation-begins",
    pubDate: "Tue, 20 May 2026 13:30:00 GMT",
    description: "Construction crews broke ground Tuesday on the riverfront park's long-planned renovation project.",
    author: "Sarah Johnson",
  },
  {
    title: "Library expands evening hours",
    link: "https://example.com/news/2026-05-18-library-hours",
    pubDate: "Sun, 18 May 2026 09:15:00 GMT",
    description: "Starting June 1st, the main branch will stay open until 9pm Monday through Thursday.",
  },
  {
    title: "Road closure on Main between 4th and 7th",
    link: "https://example.com/news/2026-05-17-main-closure",
    pubDate: "Sat, 17 May 2026 18:00:00 GMT",
    description: "Resurfacing work begins this weekend and will close that stretch through May 28.",
  },
];

const formatXml = (state, items) => {
  const lines = [
    `<?xml version="1.0" encoding="UTF-8"?>`,
    `<rss version="2.0">`,
    `  <channel>`,
    `    <title>${state?.feedName || "Untitled feed"}</title>`,
    `    <link>${state?.baseUrl || "https://example.com"}</link>`,
    `    <description>Generated by Mkfd</description>`,
    `    <lastBuildDate>${new Date().toUTCString()}</lastBuildDate>`,
  ];
  items.forEach((it) => {
    lines.push(`    <item>`);
    lines.push(`      <title>${it.title}</title>`);
    lines.push(`      <link>${it.link}</link>`);
    lines.push(`      <guid>${it.link}</guid>`);
    lines.push(`      <pubDate>${it.pubDate}</pubDate>`);
    if (it.author) lines.push(`      <author>${it.author}</author>`);
    lines.push(`      <description><![CDATA[${it.description}]]></description>`);
    lines.push(`    </item>`);
  });
  lines.push(`  </channel>`, `</rss>`);
  return lines.join("\n");
};

const escapeHtml = (s) =>
  s.replace(/[&<>]/g, (c) => (c === "&" ? "&amp;" : c === "<" ? "&lt;" : "&gt;"));

const colorizeXml = (xml) => {
  // Split into CDATA blocks, tags, and text in one pass.
  const re = /(<!\[CDATA\[[\s\S]*?\]\]>)|(<\/?[\w?!][^>]*>)/g;
  let out = "";
  let last = 0;
  let m;
  while ((m = re.exec(xml)) !== null) {
    if (m.index > last) out += escapeHtml(xml.slice(last, m.index));
    if (m[1]) {
      // CDATA block — render as a single colored span, raw text inside escaped.
      const inner = m[1].slice(9, -3);
      out +=
        '<span class="tag">&lt;![CDATA[</span>' +
        '<span class="txt">' + escapeHtml(inner) + '</span>' +
        '<span class="tag">]]&gt;</span>';
    } else {
      // Tag — extract name + attrs, color attrs.
      const raw = m[2];
      const inner = raw.slice(1, -1); // strip < >
      const nameMatch = inner.match(/^(\/?[\w?!][\w:-]*)/);
      const name = nameMatch ? nameMatch[1] : inner;
      const attrPart = inner.slice(name.length);
      const attrsColored = attrPart.replace(
        /\s+([\w-]+)(=)("[^"]*"|'[^']*')/g,
        (_, k, eq, v) =>
          ' <span class="attr">' + escapeHtml(k) + '</span>' +
          '<span class="val">' + escapeHtml(eq + v) + '</span>'
      );
      out +=
        '<span class="tag">&lt;' + escapeHtml(name) + '</span>' +
        attrsColored +
        '<span class="tag">&gt;</span>';
    }
    last = re.lastIndex;
  }
  if (last < xml.length) out += escapeHtml(xml.slice(last));
  return out;
};

const PreviewPanel = ({ state }) => {
  const [tab, setTab] = useState("items");
  const items = MOCK_PREVIEW_ITEMS;
  const valid = state && state.baseUrl;

  return (
    <div className="preview">
      <div className="preview-head">
        <h3>Live preview</h3>
        <span className="grow" />
        <span className="live">
          <span className="dot" />
          updates as you type
        </span>
      </div>
      <div className="preview-tabs">
        <button className={tab === "items" ? "active" : ""} onClick={() => setTab("items")}>
          <Icon name="list" /> Items {valid && <span style={{ color: "var(--ink-4)" }}>{items.length}</span>}
        </button>
        <button className={tab === "rss" ? "active" : ""} onClick={() => setTab("rss")}>
          <Icon name="code" /> RSS
        </button>
        <button className={tab === "atom" ? "active" : ""} onClick={() => setTab("atom")}>
          <Icon name="code" /> Atom
        </button>
        <button className={tab === "json" ? "active" : ""} onClick={() => setTab("json")}>
          <Icon name="code" /> JSON
        </button>
      </div>

      {!valid ? (
        <div className="preview-empty">
          <div className="glyph"><Icon name="rss" /></div>
          <div style={{ fontWeight: 500, color: "var(--ink-2)", marginBottom: 4 }}>
            No source yet
          </div>
          <div style={{ fontSize: 12, maxWidth: 280, margin: "0 auto" }}>
            Enter a URL above. Mkfd will fetch a sample and render items here.
          </div>
        </div>
      ) : tab === "items" ? (
        <div className="preview-items">
          {items.map((it, i) => (
            <div className="preview-item" key={i}>
              <h5>{it.title}</h5>
              <div className="meta">
                <span>{it.pubDate.replace(" GMT", "")}</span>
                {it.author && <span>· {it.author}</span>}
              </div>
              <p>{it.description}</p>
            </div>
          ))}
        </div>
      ) : tab === "rss" ? (
        <div
          className="preview-xml"
          dangerouslySetInnerHTML={{ __html: colorizeXml(formatXml(state, items)) }}
        />
      ) : tab === "atom" ? (
        <div
          className="preview-xml"
          dangerouslySetInnerHTML={{
            __html: colorizeXml(
              formatXml(state, items)
                .replace("<rss version=\"2.0\">", "<feed xmlns=\"http://www.w3.org/2005/Atom\">")
                .replace("</rss>", "</feed>")
                .replace("<channel>", "")
                .replace("</channel>", "")
                .replace(/<item>/g, "<entry>")
                .replace(/<\/item>/g, "</entry>")
                .replace(/<pubDate>/g, "<published>")
                .replace(/<\/pubDate>/g, "</published>")
            ),
          }}
        />
      ) : (
        <div className="preview-xml">
{JSON.stringify(
  {
    version: "https://jsonfeed.org/version/1.1",
    title: state?.feedName || "Untitled feed",
    home_page_url: state?.baseUrl || "https://example.com",
    feed_url: "/feeds/" + (state?.feedName || "untitled").toLowerCase().replace(/\s+/g, "-") + ".json",
    items: items.map((it) => ({
      id: it.link,
      url: it.link,
      title: it.title,
      content_text: it.description,
      date_published: new Date(it.pubDate).toISOString(),
      author: it.author ? { name: it.author } : undefined,
    })),
  },
  null,
  2
)}
        </div>
      )}
    </div>
  );
};

// ---------- Source assistant context summary card (smaller side panel during analysis) ----------

const AnalysisSidePanel = ({ analysis }) => {
  if (!analysis) return null;
  return (
    <div className="card">
      <div className="card-head">
        <span className="ic" style={{ background: "var(--brand-soft)", color: "var(--brand-ink)", borderColor: "transparent" }}>
          <Icon name="sparkles" size={14} />
        </span>
        <div>
          <h3>Source analysis</h3>
          <div className="sub">{analysis.url}</div>
        </div>
      </div>
      <div className="card-body" style={{ display: "flex", flexDirection: "column", gap: 10, fontSize: 12.5 }}>
        <div style={{ display: "flex", justifyContent: "space-between", color: "var(--ink-3)" }}>
          <span>Top recommendation</span>
          <strong style={{ color: "var(--ink)" }}>{analysis.recs[0].label}</strong>
        </div>
        <div style={{ display: "flex", justifyContent: "space-between", color: "var(--ink-3)" }}>
          <span>Confidence</span>
          <span className="mono" style={{ color: "var(--ink)" }}>
            {analysis.recs[0].confidence}%
          </span>
        </div>
        <div style={{ display: "flex", justifyContent: "space-between", color: "var(--ink-3)" }}>
          <span>Routes evaluated</span>
          <span className="mono" style={{ color: "var(--ink)" }}>
            {analysis.recs.length}
          </span>
        </div>
      </div>
    </div>
  );
};

window.PreviewPanel = PreviewPanel;
window.AnalysisSidePanel = AnalysisSidePanel;
