// Sample feed data. Realistic shape based on the FeedSummary type from the brief.

const SAMPLE_FEEDS = [
  {
    id: "cape-county-notices",
    filename: "cape-county-notices.yaml",
    title: "Cape County Notices",
    description: "Public notices for Cape Girardeau County, MO.",
    type: "scrape",
    category: "civic",
    sourceUrl: "https://capecounty.gov/legal-notices",
    sourceMethod: null,
    publicFeedUrl: "/feeds/cape-county-notices",
    enabled: true,
    favorite: true,
    tags: ["government", "local", "notices"],
    status: "healthy",
    refreshMinutes: 60,
    lastRunAt: "2026-05-23T13:42:00Z",
    lastRunRelative: "8 min ago",
    lastSuccessAt: "2026-05-23T13:42:00Z",
    lastItemCount: 24,
    lastNewItemCount: 2,
    secrets: { protected: false, env: false, plain: false },
    origin: { type: "local" },
  },
  {
    id: "github-releases",
    filename: "github-releases.yaml",
    title: "GitHub Releases",
    description: "Releases for a watched GitHub repository.",
    type: "rest",
    category: "developer",
    sourceUrl: "https://api.github.com/repos/oven-sh/bun/releases",
    sourceMethod: "GET",
    publicFeedUrl: "/feeds/github-releases",
    enabled: true,
    favorite: true,
    tags: ["github", "releases", "bun"],
    status: "healthy",
    refreshMinutes: 30,
    lastRunRelative: "2 min ago",
    lastItemCount: 30,
    lastNewItemCount: 1,
    secrets: { protected: true, env: false, plain: false },
    origin: { type: "community", catalogId: "github-releases" },
  },
  {
    id: "hacker-news-front",
    filename: "hacker-news-front.yaml",
    title: "Hacker News — Front Page",
    description: "HN top stories scraped from the front page.",
    type: "scrape",
    category: "news",
    sourceUrl: "https://news.ycombinator.com/",
    publicFeedUrl: "/feeds/hacker-news-front",
    enabled: true,
    favorite: false,
    tags: ["tech", "news", "daily"],
    status: "healthy",
    refreshMinutes: 15,
    lastRunRelative: "4 min ago",
    lastItemCount: 30,
    lastNewItemCount: 6,
    secrets: { protected: false, env: false, plain: false },
    origin: { type: "community", catalogId: "hn-front" },
  },
  {
    id: "oldham-athletic",
    filename: "oldham-athletic.yaml",
    title: "Oldham Athletic — Club News",
    description: "Football club news posts.",
    type: "scrape",
    category: "sports",
    sourceUrl: "https://www.oldhamathletic.co.uk/news/",
    publicFeedUrl: "/feeds/oldham-athletic",
    enabled: true,
    favorite: false,
    tags: ["football", "club", "uk"],
    status: "warning",
    statusDetail: "Selector matched 0 elements on last run.",
    refreshMinutes: 120,
    lastRunRelative: "1 h ago",
    lastItemCount: 0,
    lastNewItemCount: 0,
    secrets: { protected: false, env: false, plain: false },
    origin: { type: "local" },
  },
  {
    id: "private-monitoring-api",
    filename: "private-monitoring-api.yaml",
    title: "Private Monitoring API",
    description: "Internal status events from our monitoring stack.",
    type: "rest",
    category: "monitoring",
    sourceUrl: "https://monitor.internal.example.com/api/v1/events",
    sourceMethod: "GET",
    publicFeedUrl: "/feeds/private-monitoring-api",
    enabled: true,
    favorite: false,
    tags: ["internal", "work", "alerts"],
    status: "healthy",
    refreshMinutes: 5,
    lastRunRelative: "just now",
    lastItemCount: 12,
    lastNewItemCount: 3,
    secrets: { protected: true, env: true, plain: false },
    origin: { type: "local" },
  },
  {
    id: "city-council-agendas",
    filename: "city-council-agendas.yaml",
    title: "City Council Agendas",
    description: "PDFs dropped into /watch/agendas by a cron upstream.",
    type: "filesystem",
    category: "civic",
    sourceUrl: "/app/watch/agendas",
    publicFeedUrl: "/feeds/city-council-agendas",
    enabled: true,
    favorite: false,
    tags: ["government", "agenda", "pdf"],
    status: "neverRun",
    refreshMinutes: 360,
    lastRunRelative: "never",
    lastItemCount: null,
    secrets: { protected: false, env: false, plain: false },
    origin: { type: "local" },
  },
  {
    id: "bun-graphql-repo",
    filename: "bun-graphql-repo.yaml",
    title: "Repo Releases (GraphQL)",
    description: "Repository releases via GitHub's GraphQL API.",
    type: "graphql",
    category: "developer",
    sourceUrl: "https://api.github.com/graphql",
    sourceMethod: "POST",
    publicFeedUrl: "/feeds/bun-graphql-repo",
    enabled: true,
    favorite: false,
    tags: ["github", "monitoring"],
    status: "error",
    statusDetail: "Last 3 runs returned HTTP 401 (bad token).",
    refreshMinutes: 60,
    lastRunRelative: "20 min ago",
    lastErrorAt: "2026-05-23T13:30:00Z",
    lastItemCount: 0,
    secrets: { protected: true, env: false, plain: false },
    origin: { type: "local" },
  },
  {
    id: "family-gmail",
    filename: "family-gmail.yaml",
    title: "Family Gmail — Receipts",
    description: "Receipts label folder from family Gmail account.",
    type: "email",
    category: "personal",
    sourceUrl: "imap.gmail.com / INBOX/Receipts",
    publicFeedUrl: "/feeds/family-gmail",
    enabled: true,
    favorite: false,
    tags: ["email", "personal", "receipts"],
    status: "warning",
    statusDetail: "Password stored as plain string in config.",
    refreshMinutes: 30,
    lastRunRelative: "12 min ago",
    lastItemCount: 4,
    lastNewItemCount: 0,
    secrets: { protected: false, env: false, plain: true },
    origin: { type: "local" },
  },
  {
    id: "library-events",
    filename: "library-events.yaml",
    title: "Local Library Events",
    description: "Public library iCal events feed.",
    type: "calendar",
    category: "civic",
    sourceUrl: "https://library.example.org/events.ics",
    publicFeedUrl: "/feeds/library-events",
    enabled: false,
    favorite: false,
    tags: ["events", "library", "kids"],
    status: "disabled",
    refreshMinutes: 720,
    lastRunRelative: "3 days ago",
    lastItemCount: 18,
    lastNewItemCount: 0,
    secrets: { protected: false, env: false, plain: false },
    origin: { type: "local" },
  },
  {
    id: "vendor-sitemap",
    filename: "vendor-sitemap.yaml",
    title: "Vendor Sitemap Watch",
    description: "Watches a vendor's sitemap for new product URLs.",
    type: "sitemap",
    category: "commerce",
    sourceUrl: "https://shop.example.com/sitemap.xml",
    publicFeedUrl: "/feeds/vendor-sitemap",
    enabled: true,
    favorite: false,
    tags: ["ecommerce", "watch"],
    status: "healthy",
    refreshMinutes: 240,
    lastRunRelative: "1 h ago",
    lastItemCount: 240,
    lastNewItemCount: 0,
    secrets: { protected: false, env: false, plain: false },
    origin: { type: "community", catalogId: "sitemap-watch" },
  },
  {
    id: "deploy-notifications",
    filename: "deploy-notifications.yaml",
    title: "Deploy Notifications",
    description: "Inbound webhook from our CI pipeline.",
    type: "webhook",
    category: "automation",
    sourceUrl: "/webhook-feeds/deployments",
    publicFeedUrl: "/feeds/deploy-notifications",
    enabled: true,
    favorite: true,
    tags: ["deploy", "ci-cd", "work"],
    status: "healthy",
    refreshMinutes: null,
    lastRunRelative: "12 min ago",
    lastItemCount: 87,
    lastNewItemCount: 3,
    secrets: { protected: false, env: true, plain: false },
    origin: { type: "local" },
  },
  {
    id: "reddit-selfhosted",
    filename: "reddit-selfhosted.yaml",
    title: "r/selfhosted",
    description: "Top posts from r/selfhosted with the existing-feed transformer.",
    type: "scrape",
    category: "developer",
    sourceUrl: "https://old.reddit.com/r/selfhosted/",
    publicFeedUrl: "/feeds/reddit-selfhosted",
    enabled: true,
    favorite: false,
    tags: ["reddit", "selfhost", "weekend"],
    status: "healthy",
    refreshMinutes: 60,
    lastRunRelative: "31 min ago",
    lastItemCount: 25,
    lastNewItemCount: 4,
    secrets: { protected: false, env: false, plain: false },
    origin: { type: "community", catalogId: "reddit-sub" },
  },
];

window.SAMPLE_FEEDS = SAMPLE_FEEDS;
