import * as cheerio from 'cheerio';
import * as RSS from 'rss';
import { CSSTarget } from "../models/CSSTarget.model";
import { timestampToDate } from "./data-handler.utility";

//TODO: ADD HTML STRIPPING TO EACH TARGET 
export function buildRSS(res: any, article?:
        { iterator: CSSTarget | { selector: string, attribute?: string, stripHtml?: boolean}, 
          title?: CSSTarget | { selector: string, attribute?: string, stripHtml?: boolean },
          link?: CSSTarget | { selector: string, attribute?: string, stripHtml?: boolean },
          date?: CSSTarget | { selector: string, attribute?: string, stripHtml?: boolean } },
          title?: CSSTarget | { selector: string, attribute?: string, stripHtml?: boolean }, 
          link?: CSSTarget | { selector: string, attribute?: string, stripHtml?: boolean }, 
          date?: CSSTarget | { selector: string, attribute?: string, stripHtml?: boolean }, 
          timestamp?: boolean): string {
        let input: Array<any> = [];
        const $ = cheerio.load(res);
        if (article) {
            $(article.iterator.selector).each((i, data) => {
                input.push({
                    title: !!article.title?.attribute ? $(data).find(article.title?.selector)?.attr(article.title?.attribute) : $(data).find(article.title?.selector)?.text(),
                    url: !!article.link?.attribute ? $(data).find(article.link?.selector)?.attr(article.link?.attribute) : $(data).find(article.link?.selector)?.text(),
                    date: !!article.date?.attribute ? $(data).find(article.date?.selector)?.attr(article.date?.attribute) : $(data).find(article.date?.selector)?.text()
                })
                console.log(input);
            })
        }
        if (title) {
            $(title?.selector).each((i, data) => {
                input[i].title = $(data).attr(title.attribute) ?? $(data).text();
            })
        }
        if (link) {
            $(link?.selector).each((i, data) => {
                input[i].url = $(data).attr(link.attribute) ?? $(data).text();
            })
        }
        if (date) {
            $(date?.selector).each((i, data) => {
                const dateTime = $(data).text();
                input[i].date = $(data).attr(date.attribute) ?? dateTime;
                if(timestamp) input[i].date = timestampToDate(dateTime);
            })
        }
    
        const feed = new RSS({
            title: $('title')?.text(),
            description: $('meta[property="twitter:description"]')?.attr('content'),
            author: "mkfd",
            generator: 'Generated by mkfd',
        });
    
        for (const article of input) {
            feed.item({
                title: article.title,
                description: null,
                url: article.url,
                guid: article.url??article.title,
                categories: null,
                author: null,
                date: article.date,
                lat: null,
                long: null,
                custom_elements: null,
                enclosure: null
            });
        }
        return feed.xml({ indent: true });
}