import React, { useState } from "react";

interface PreviewPanelProps {
  feedName?: string;
  sourceUrl?: string;
}

const SAMPLE_ITEMS = [
  {
    title: "Sample article title",
    link: "https://example.com/article-1",
    pubDate: new Date(Date.now() - 3600000).toUTCString(),
    description: "A brief excerpt from the article appears here.",
  },
  {
    title: "Another interesting post",
    link: "https://example.com/article-2",
    pubDate: new Date(Date.now() - 7200000).toUTCString(),
    description: "This is a sample description for the second item.",
  },
];

export const PreviewPanel: React.FC<PreviewPanelProps> = ({
  feedName = "Untitled Feed",
  sourceUrl = "https://example.com",
}) => {
  const [tab, setTab] = useState<"items" | "rss">("items");

  const rssXml = `<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0">
  <channel>
    <title>${feedName}</title>
    <link>${sourceUrl}</link>
    <description>Feed generated by mkfd</description>
${SAMPLE_ITEMS.map((item) => `    <item>
      <title>${item.title}</title>
      <link>${item.link}</link>
      <pubDate>${item.pubDate}</pubDate>
      <description>${item.description}</description>
    </item>`).join("\n")}
  </channel>
</rss>`;

  return (
    <div style={{ display: "flex", flexDirection: "column", height: "100%", background: "var(--wb-card)", color: "hsl(var(--foreground))" }}>
      <div style={{ padding: "12px 14px", borderBottom: "1px solid hsl(var(--border))" }}>
        <div className="workbench-label" style={{ color: "hsl(var(--muted-foreground))", marginBottom: 8 }}>Raw Data Output Console</div>
        <div style={{ display: "flex", gap: 2 }}>
          <button
            type="button"
            onClick={() => setTab("items")}
            style={{ padding: "3px 10px", borderRadius: "6px 0 0 6px", border: "1px solid hsl(var(--border))", fontSize: 12, cursor: "pointer", background: tab === "items" ? "hsl(var(--primary))" : "transparent", color: tab === "items" ? "hsl(var(--primary-foreground))" : "hsl(var(--muted-foreground))" }}
          >
            Items
          </button>
          <button
            type="button"
            onClick={() => setTab("rss")}
            style={{ padding: "3px 10px", borderRadius: "0 6px 6px 0", border: "1px solid hsl(var(--border))", borderLeft: 0, fontSize: 12, cursor: "pointer", background: tab === "rss" ? "hsl(var(--primary))" : "transparent", color: tab === "rss" ? "hsl(var(--primary-foreground))" : "hsl(var(--muted-foreground))" }}
          >
            RSS
          </button>
        </div>
      </div>
      <div style={{ flex: 1, overflow: "auto", padding: 14 }}>
        {tab === "items" ? (
          <div style={{ display: "flex", flexDirection: "column", gap: 10 }}>
            {sourceUrl && (
              <div style={{ fontSize: 11, color: "hsl(var(--muted-foreground))", marginBottom: 4, fontFamily: "var(--feeds-font-mono, monospace)" }}>
                {`source="${sourceUrl}"  items=${SAMPLE_ITEMS.length}`}
              </div>
            )}
            {SAMPLE_ITEMS.map((item, i) => (
              <div
                key={i}
                style={{
                  background: "hsl(var(--muted))",
                  border: "1px solid hsl(var(--border))",
                  borderRadius: 8,
                  padding: "10px 12px",
                }}
              >
                <div style={{ fontWeight: 600, fontSize: 13, marginBottom: 4 }}>{item.title}</div>
                <div style={{ fontSize: 11, color: "hsl(var(--muted-foreground))", marginBottom: 4 }}>{item.description}</div>
                <div style={{ fontSize: 10, color: "hsl(var(--muted-foreground))", fontFamily: "var(--feeds-font-mono, monospace)" }}>
                  {item.pubDate}
                </div>
              </div>
            ))}
          </div>
        ) : (
          <pre
            style={{
              fontSize: 11,
              fontFamily: "var(--feeds-font-mono, monospace)",
              color: "hsl(var(--foreground))",
              whiteSpace: "pre-wrap",
              wordBreak: "break-all",
              margin: 0,
            }}
          >
            {rssXml}
          </pre>
        )}
      </div>
    </div>
  );
};
